go_library(
    name = "driver",
    srcs = ["please_driver.go", "module.go"],
    deps = ["//third_party/go/golang.org/x/tools:tools", "//third_party/go/golang.org/x/net", "//resolve/knownimports"],
    visibility = ["//resolve/..."],
)