go_library(
    name = "rules",
    srcs = [
        "format.go",
        "read.go",
    ],
    visibility = ["//resolve/..."],
    deps = [
        "//resolve",
        "//resolve/model",
        "//third_party/go:github.com.bazelbuild.buildtools",
    ],
)
