go_library(
    name = "rules",
    srcs = [
        "format.go",
        "read.go",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//resolve",
        "//resolve/model",
        "//third_party/go:buildtools",
    ],
)
