go_library(
    name = "rules",
    srcs = ["rules.go", "read.go"],
    deps = ["//resolve/model", "//resolve", "//third_party/go:github.com.bazelbuild.buildtools"],
    visibility = ["//resolve/..."],
)