name: Go

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v .

    # The following is a bunch of test cases...
    - name: Test github.com/stretchr/testify -v v1.6.1
      working-directory: ./examplerepo
      run: ../go-deps -m github.com/stretchr/testify -v v1.6.1 && ./pleasew build //third_party/...
      
    - name: Test github.com/grpc-ecosystem/grpc-gateway -v v1.16.0
      working-directory: ./examplerepo
      run: ../go-deps -m github.com/grpc-ecosystem/grpc-gateway -v v1.16.0 && ./pleasew build //third_party/...
      
    - name: Test github.com/jamesjarvis/go-deps
      working-directory: ./examplerepo
      run: ../go-deps -m github.com/jamesjarvis/go-deps && ./pleasew build //third_party/...
